### ISSUE TITLE
Suggestion - Manual tab-theme

### ISSUE THREAD

**Issue by Vivahex** [liri-browser/liri-browser#103]
As suggested on G+, just moving to an issue here:

Option to set custom theme-colour using hex codes for a domain name, could be a page in the settings with a list of these. 
If (or when) the website is updated to include its own theme-colour, there could be an option on a per site basis to choose to override the default theme-colour with the custom one, or have it set by the site.

**Comment by Vivahex** [comment]
I got a little bored so decided to mock up a concept of how I'd imagine it looking.
The top of the image contains a new button for "Custom Theme Colours" which brings you to the second page, shown below. 
A name for the site chosen by the user, the main domain of which to theme (so anything after .com/ is still themed), the hex code set by the user with a preview of the colour they have selected, and an option to override the colour provided by the server.

Disclaimer: THIS IS JUST AN IDEA, Please don't hate for the spacing or anything, just a quick mockup of how I personally imagine it. It can be implemented in any way by the developers.
![3](https://cloud.githubusercontent.com/assets/9933159/10248290/62766e02-6916-11e5-99e3-a6994f7ef85a.png)

**Comment by VirusKA** [comment]
great idea!

**Comment by pierremtb** [comment]
Hey, I started working on this feature. The backend is done, so the only thing left to do is to write the settings part. For now only youtube.com is added to the ListModel : 
![capture du 2015-10-04 00 50 20](https://cloud.githubusercontent.com/assets/10795683/10265476/5112213e-6a32-11e5-8cd2-e832fc27b3c2.png)

**Comment by Vivahex** [comment]
Looks fantastic! Glad to see it's working out okay :) wasn't sure how easy this would be to implement.

**Comment by VirusKA** [comment]
@pierremtb  woah browser looking better and better

**Comment by pierremtb** [comment]
Finished this tonight. I added a presets category, that we set, and can be overwritten by custom entries. These presets are in a JSON array : 
[ \
            {'domain':'facebook.com', 'color': '#3b5998'} , \
            {'domain':'linkedin.com', 'color': '#646464'} , \
            {'domain':'twitter.com', 'color': '#00aced'} \
        ]
We should make this list "public", so everyone could add his favorite sites, in order to build a huge database.

![capture du 2015-10-05 00 12 27](https://cloud.githubusercontent.com/assets/10795683/10270581/2755109e-6af6-11e5-9a99-d6c008dc0a25.png)
![capture du 2015-10-05 00 12 24](https://cloud.githubusercontent.com/assets/10795683/10270582/2a360fb6-6af6-11e5-8d74-50ff17a76c6d.png)
![capture du 2015-10-05 00 12 18](https://cloud.githubusercontent.com/assets/10795683/10270583/2d190080-6af6-11e5-84aa-a434719402d4.png)

**Comment by jmc-figueira** [comment]
While, nevertheless, the progress shown is amazing, on my machine it's still not working right, not only do the themes not apply, but this also happens when trying to use the color chooser:

![captura de tela 2015-10-05 00 23 13](https://cloud.githubusercontent.com/assets/6634716/10270879/84fb5d92-6af7-11e5-9654-3df50f251752.png)

Currently on OS X El Capitan.

**Comment by VirusKA** [comment]
This sorta off topic, but how'd you get Liri Browser to work from the source? never works for me.

**Comment by jmc-figueira** [comment]
By just compiling with Qt Creator. You need the qml-material external lib as well: https://github.com/papyros/qml-material

**Comment by VirusKA** [comment]
It always says `command not found: run`

**Comment by VirusKA** [comment]
wait nvm

**Comment by pierremtb** [comment]
@jmc-figueira Just tested on my El Capitan, and the custom themes are applying.. Do you have the dark theme on ? Because the dark theme overwrite any custom tab color.

**Comment by tim-sueberkrueb** [comment]
@pierremtb I think it would be better to have this as a tab on the Desktop.

**Comment by pierremtb** [comment]
@tim-sueberkrueb You're probably right

**Comment by tim-sueberkrueb** [comment]
@pierremtb but leave the subpage for the mobile mode :) You could do it the way we do with the settings.

**Comment by pierremtb** [comment]
@tim-sueberkrueb As suggested, I moved it to a new tab : 
![capture du 2015-10-05 20 15 41](https://cloud.githubusercontent.com/assets/10795683/10289336/1e53b8d0-6b9e-11e5-9f36-48fc5139034e.png)

**Comment by tim-sueberkrueb** [comment]
+1

**Comment by pierremtb** [comment]
It would be great to create a database. Here is a Gist, please add your favorite websites header colors : 
https://gist.github.com/pierremtb/829db60ad0df3a3fed6e
